//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AAT_DTF_ecsModel", "fk_filter_list_job1", "job", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ECSUser.job), "filter_list", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ECSUser.filter_list), true)]
[assembly: EdmRelationshipAttribute("AAT_DTF_ecsModel", "fk_job_settings_job1", "job", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ECSUser.job), "job_settings", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ECSUser.job_settings), true)]
[assembly: EdmRelationshipAttribute("AAT_DTF_ecsModel", "fk_testrun_job1", "job", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ECSUser.job), "testrun", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ECSUser.testrun), true)]

#endregion

namespace ECSUser
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AAT_DTF_ecsEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AAT_DTF_ecsEntities2 object using the connection string found in the 'AAT_DTF_ecsEntities2' section of the application configuration file.
        /// </summary>
        public AAT_DTF_ecsEntities2() : base("name=AAT_DTF_ecsEntities2", "AAT_DTF_ecsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AAT_DTF_ecsEntities2 object.
        /// </summary>
        public AAT_DTF_ecsEntities2(string connectionString) : base(connectionString, "AAT_DTF_ecsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AAT_DTF_ecsEntities2 object.
        /// </summary>
        public AAT_DTF_ecsEntities2(EntityConnection connection) : base(connection, "AAT_DTF_ecsEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<filter_list> filter_list
        {
            get
            {
                if ((_filter_list == null))
                {
                    _filter_list = base.CreateObjectSet<filter_list>("filter_list");
                }
                return _filter_list;
            }
        }
        private ObjectSet<filter_list> _filter_list;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<job> jobs
        {
            get
            {
                if ((_jobs == null))
                {
                    _jobs = base.CreateObjectSet<job>("jobs");
                }
                return _jobs;
            }
        }
        private ObjectSet<job> _jobs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<job_settings> job_settings
        {
            get
            {
                if ((_job_settings == null))
                {
                    _job_settings = base.CreateObjectSet<job_settings>("job_settings");
                }
                return _job_settings;
            }
        }
        private ObjectSet<job_settings> _job_settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<o> os
        {
            get
            {
                if ((_os == null))
                {
                    _os = base.CreateObjectSet<o>("os");
                }
                return _os;
            }
        }
        private ObjectSet<o> _os;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<schema_info> schema_info
        {
            get
            {
                if ((_schema_info == null))
                {
                    _schema_info = base.CreateObjectSet<schema_info>("schema_info");
                }
                return _schema_info;
            }
        }
        private ObjectSet<schema_info> _schema_info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<testrun> testruns
        {
            get
            {
                if ((_testruns == null))
                {
                    _testruns = base.CreateObjectSet<testrun>("testruns");
                }
                return _testruns;
            }
        }
        private ObjectSet<testrun> _testruns;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the filter_list EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofilter_list(filter_list filter_list)
        {
            base.AddObject("filter_list", filter_list);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the jobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojobs(job job)
        {
            base.AddObject("jobs", job);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the job_settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojob_settings(job_settings job_settings)
        {
            base.AddObject("job_settings", job_settings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the os EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToos(o o)
        {
            base.AddObject("os", o);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the schema_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToschema_info(schema_info schema_info)
        {
            base.AddObject("schema_info", schema_info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the testruns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotestruns(testrun testrun)
        {
            base.AddObject("testruns", testrun);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="filter_list")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class filter_list : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new filter_list object.
        /// </summary>
        /// <param name="jobID">Initial value of the JobID property.</param>
        /// <param name="fullPath">Initial value of the FullPath property.</param>
        public static filter_list Createfilter_list(global::System.String jobID, global::System.String fullPath)
        {
            filter_list filter_list = new filter_list();
            filter_list.JobID = jobID;
            filter_list.FullPath = fullPath;
            return filter_list;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                if (_JobID != value)
                {
                    OnJobIDChanging(value);
                    ReportPropertyChanging("JobID");
                    _JobID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("JobID");
                    OnJobIDChanged();
                }
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullPath
        {
            get
            {
                return _FullPath;
            }
            set
            {
                if (_FullPath != value)
                {
                    OnFullPathChanging(value);
                    ReportPropertyChanging("FullPath");
                    _FullPath = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FullPath");
                    OnFullPathChanged();
                }
            }
        }
        private global::System.String _FullPath;
        partial void OnFullPathChanging(global::System.String value);
        partial void OnFullPathChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_filter_list_job1", "job")]
        public job job
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_filter_list_job1", "job").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_filter_list_job1", "job").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<job> jobReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_filter_list_job1", "job");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<job>("AAT_DTF_ecsModel.fk_filter_list_job1", "job", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="job")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class job : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new job object.
        /// </summary>
        /// <param name="jobID">Initial value of the JobID property.</param>
        /// <param name="submitter">Initial value of the Submitter property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="server">Initial value of the Server property.</param>
        /// <param name="progress">Initial value of the Progress property.</param>
        /// <param name="submitted">Initial value of the Submitted property.</param>
        /// <param name="bandwidth">Initial value of the Bandwidth property.</param>
        /// <param name="totalErrors">Initial value of the TotalErrors property.</param>
        public static job Createjob(global::System.String jobID, global::System.String submitter, global::System.String status, global::System.String server, global::System.Double progress, global::System.DateTime submitted, global::System.Int64 bandwidth, global::System.Int32 totalErrors)
        {
            job job = new job();
            job.JobID = jobID;
            job.Submitter = submitter;
            job.Status = status;
            job.Server = server;
            job.Progress = progress;
            job.Submitted = submitted;
            job.Bandwidth = bandwidth;
            job.TotalErrors = totalErrors;
            return job;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                if (_JobID != value)
                {
                    OnJobIDChanging(value);
                    ReportPropertyChanging("JobID");
                    _JobID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("JobID");
                    OnJobIDChanged();
                }
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Submitter
        {
            get
            {
                return _Submitter;
            }
            set
            {
                OnSubmitterChanging(value);
                ReportPropertyChanging("Submitter");
                _Submitter = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Submitter");
                OnSubmitterChanged();
            }
        }
        private global::System.String _Submitter;
        partial void OnSubmitterChanging(global::System.String value);
        partial void OnSubmitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserFullName
        {
            get
            {
                return _UserFullName;
            }
            set
            {
                OnUserFullNameChanging(value);
                ReportPropertyChanging("UserFullName");
                _UserFullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserFullName");
                OnUserFullNameChanged();
            }
        }
        private global::System.String _UserFullName;
        partial void OnUserFullNameChanging(global::System.String value);
        partial void OnUserFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Server
        {
            get
            {
                return _Server;
            }
            set
            {
                OnServerChanging(value);
                ReportPropertyChanging("Server");
                _Server = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Server");
                OnServerChanged();
            }
        }
        private global::System.String _Server;
        partial void OnServerChanging(global::System.String value);
        partial void OnServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Progress
        {
            get
            {
                return _Progress;
            }
            set
            {
                OnProgressChanging(value);
                ReportPropertyChanging("Progress");
                _Progress = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Progress");
                OnProgressChanged();
            }
        }
        private global::System.Double _Progress;
        partial void OnProgressChanging(global::System.Double value);
        partial void OnProgressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Submitted
        {
            get
            {
                return _Submitted;
            }
            set
            {
                OnSubmittedChanging(value);
                ReportPropertyChanging("Submitted");
                _Submitted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Submitted");
                OnSubmittedChanged();
            }
        }
        private global::System.DateTime _Submitted;
        partial void OnSubmittedChanging(global::System.DateTime value);
        partial void OnSubmittedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Bandwidth
        {
            get
            {
                return _Bandwidth;
            }
            set
            {
                OnBandwidthChanging(value);
                ReportPropertyChanging("Bandwidth");
                _Bandwidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bandwidth");
                OnBandwidthChanged();
            }
        }
        private global::System.Int64 _Bandwidth;
        partial void OnBandwidthChanging(global::System.Int64 value);
        partial void OnBandwidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> ETA
        {
            get
            {
                return _ETA;
            }
            set
            {
                OnETAChanging(value);
                ReportPropertyChanging("ETA");
                _ETA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ETA");
                OnETAChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _ETA;
        partial void OnETAChanging(Nullable<global::System.TimeSpan> value);
        partial void OnETAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalErrors
        {
            get
            {
                return _TotalErrors;
            }
            set
            {
                OnTotalErrorsChanging(value);
                ReportPropertyChanging("TotalErrors");
                _TotalErrors = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalErrors");
                OnTotalErrorsChanged();
            }
        }
        private global::System.Int32 _TotalErrors;
        partial void OnTotalErrorsChanging(global::System.Int32 value);
        partial void OnTotalErrorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TotalCases
        {
            get
            {
                return _TotalCases;
            }
            set
            {
                OnTotalCasesChanging(value);
                ReportPropertyChanging("TotalCases");
                _TotalCases = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TotalCases");
                OnTotalCasesChanged();
            }
        }
        private global::System.String _TotalCases;
        partial void OnTotalCasesChanging(global::System.String value);
        partial void OnTotalCasesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_filter_list_job1", "filter_list")]
        public EntityCollection<filter_list> filter_list
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<filter_list>("AAT_DTF_ecsModel.fk_filter_list_job1", "filter_list");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<filter_list>("AAT_DTF_ecsModel.fk_filter_list_job1", "filter_list", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_job_settings_job1", "job_settings")]
        public job_settings job_settings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job_settings>("AAT_DTF_ecsModel.fk_job_settings_job1", "job_settings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job_settings>("AAT_DTF_ecsModel.fk_job_settings_job1", "job_settings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<job_settings> job_settingsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job_settings>("AAT_DTF_ecsModel.fk_job_settings_job1", "job_settings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<job_settings>("AAT_DTF_ecsModel.fk_job_settings_job1", "job_settings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_testrun_job1", "testrun")]
        public EntityCollection<testrun> testruns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<testrun>("AAT_DTF_ecsModel.fk_testrun_job1", "testrun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<testrun>("AAT_DTF_ecsModel.fk_testrun_job1", "testrun", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="job_settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class job_settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new job_settings object.
        /// </summary>
        /// <param name="jobID">Initial value of the JobID property.</param>
        /// <param name="officialRun">Initial value of the OfficialRun property.</param>
        /// <param name="segmentSize">Initial value of the SegmentSize property.</param>
        /// <param name="disableVMOnJobCompleted">Initial value of the DisableVMOnJobCompleted property.</param>
        /// <param name="product">Initial value of the Product property.</param>
        /// <param name="useESXAgent">Initial value of the UseESXAgent property.</param>
        /// <param name="logCER">Initial value of the LogCER property.</param>
        /// <param name="imageIndex">Initial value of the ImageIndex property.</param>
        public static job_settings Createjob_settings(global::System.String jobID, global::System.Boolean officialRun, global::System.Int64 segmentSize, global::System.Boolean disableVMOnJobCompleted, global::System.String product, global::System.Boolean useESXAgent, global::System.Boolean logCER, global::System.Int32 imageIndex)
        {
            job_settings job_settings = new job_settings();
            job_settings.JobID = jobID;
            job_settings.OfficialRun = officialRun;
            job_settings.SegmentSize = segmentSize;
            job_settings.DisableVMOnJobCompleted = disableVMOnJobCompleted;
            job_settings.Product = product;
            job_settings.UseESXAgent = useESXAgent;
            job_settings.LogCER = logCER;
            job_settings.ImageIndex = imageIndex;
            return job_settings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                if (_JobID != value)
                {
                    OnJobIDChanging(value);
                    ReportPropertyChanging("JobID");
                    _JobID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("JobID");
                    OnJobIDChanged();
                }
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomListFile
        {
            get
            {
                return _CustomListFile;
            }
            set
            {
                OnCustomListFileChanging(value);
                ReportPropertyChanging("CustomListFile");
                _CustomListFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomListFile");
                OnCustomListFileChanged();
            }
        }
        private global::System.String _CustomListFile;
        partial void OnCustomListFileChanging(global::System.String value);
        partial void OnCustomListFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuildID
        {
            get
            {
                return _BuildID;
            }
            set
            {
                OnBuildIDChanging(value);
                ReportPropertyChanging("BuildID");
                _BuildID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuildID");
                OnBuildIDChanged();
            }
        }
        private global::System.String _BuildID;
        partial void OnBuildIDChanging(global::System.String value);
        partial void OnBuildIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailFrom
        {
            get
            {
                return _EmailFrom;
            }
            set
            {
                OnEmailFromChanging(value);
                ReportPropertyChanging("EmailFrom");
                _EmailFrom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailFrom");
                OnEmailFromChanged();
            }
        }
        private global::System.String _EmailFrom;
        partial void OnEmailFromChanging(global::System.String value);
        partial void OnEmailFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailServer
        {
            get
            {
                return _EmailServer;
            }
            set
            {
                OnEmailServerChanging(value);
                ReportPropertyChanging("EmailServer");
                _EmailServer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailServer");
                OnEmailServerChanged();
            }
        }
        private global::System.String _EmailServer;
        partial void OnEmailServerChanging(global::System.String value);
        partial void OnEmailServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailTo
        {
            get
            {
                return _EmailTo;
            }
            set
            {
                OnEmailToChanging(value);
                ReportPropertyChanging("EmailTo");
                _EmailTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailTo");
                OnEmailToChanged();
            }
        }
        private global::System.String _EmailTo;
        partial void OnEmailToChanging(global::System.String value);
        partial void OnEmailToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomLabel
        {
            get
            {
                return _CustomLabel;
            }
            set
            {
                OnCustomLabelChanging(value);
                ReportPropertyChanging("CustomLabel");
                _CustomLabel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomLabel");
                OnCustomLabelChanged();
            }
        }
        private global::System.String _CustomLabel;
        partial void OnCustomLabelChanging(global::System.String value);
        partial void OnCustomLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean OfficialRun
        {
            get
            {
                return _OfficialRun;
            }
            set
            {
                OnOfficialRunChanging(value);
                ReportPropertyChanging("OfficialRun");
                _OfficialRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfficialRun");
                OnOfficialRunChanged();
            }
        }
        private global::System.Boolean _OfficialRun;
        partial void OnOfficialRunChanging(global::System.Boolean value);
        partial void OnOfficialRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VMLimit
        {
            get
            {
                return _VMLimit;
            }
            set
            {
                OnVMLimitChanging(value);
                ReportPropertyChanging("VMLimit");
                _VMLimit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VMLimit");
                OnVMLimitChanged();
            }
        }
        private Nullable<global::System.Int32> _VMLimit;
        partial void OnVMLimitChanging(Nullable<global::System.Int32> value);
        partial void OnVMLimitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SegmentSize
        {
            get
            {
                return _SegmentSize;
            }
            set
            {
                OnSegmentSizeChanging(value);
                ReportPropertyChanging("SegmentSize");
                _SegmentSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SegmentSize");
                OnSegmentSizeChanged();
            }
        }
        private global::System.Int64 _SegmentSize;
        partial void OnSegmentSizeChanging(global::System.Int64 value);
        partial void OnSegmentSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DisableVMOnJobCompleted
        {
            get
            {
                return _DisableVMOnJobCompleted;
            }
            set
            {
                OnDisableVMOnJobCompletedChanging(value);
                ReportPropertyChanging("DisableVMOnJobCompleted");
                _DisableVMOnJobCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisableVMOnJobCompleted");
                OnDisableVMOnJobCompletedChanged();
            }
        }
        private global::System.Boolean _DisableVMOnJobCompleted;
        partial void OnDisableVMOnJobCompletedChanging(global::System.Boolean value);
        partial void OnDisableVMOnJobCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseESXAgent
        {
            get
            {
                return _UseESXAgent;
            }
            set
            {
                OnUseESXAgentChanging(value);
                ReportPropertyChanging("UseESXAgent");
                _UseESXAgent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseESXAgent");
                OnUseESXAgentChanged();
            }
        }
        private global::System.Boolean _UseESXAgent;
        partial void OnUseESXAgentChanging(global::System.Boolean value);
        partial void OnUseESXAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LogCER
        {
            get
            {
                return _LogCER;
            }
            set
            {
                OnLogCERChanging(value);
                ReportPropertyChanging("LogCER");
                _LogCER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogCER");
                OnLogCERChanged();
            }
        }
        private global::System.Boolean _LogCER;
        partial void OnLogCERChanging(global::System.Boolean value);
        partial void OnLogCERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageIndex
        {
            get
            {
                return _ImageIndex;
            }
            set
            {
                OnImageIndexChanging(value);
                ReportPropertyChanging("ImageIndex");
                _ImageIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageIndex");
                OnImageIndexChanged();
            }
        }
        private global::System.Int32 _ImageIndex;
        partial void OnImageIndexChanging(global::System.Int32 value);
        partial void OnImageIndexChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_job_settings_job1", "job")]
        public job job
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_job_settings_job1", "job").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_job_settings_job1", "job").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<job> jobReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_job_settings_job1", "job");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<job>("AAT_DTF_ecsModel.fk_job_settings_job1", "job", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="o")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class o : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new o object.
        /// </summary>
        /// <param name="oSVersion">Initial value of the OSVersion property.</param>
        /// <param name="oSType">Initial value of the OSType property.</param>
        /// <param name="memorySize">Initial value of the MemorySize property.</param>
        /// <param name="netConnectionType">Initial value of the NetConnectionType property.</param>
        public static o Createo(global::System.String oSVersion, global::System.String oSType, global::System.Int32 memorySize, global::System.String netConnectionType)
        {
            o o = new o();
            o.OSVersion = oSVersion;
            o.OSType = oSType;
            o.MemorySize = memorySize;
            o.NetConnectionType = netConnectionType;
            return o;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSVersion
        {
            get
            {
                return _OSVersion;
            }
            set
            {
                if (_OSVersion != value)
                {
                    OnOSVersionChanging(value);
                    ReportPropertyChanging("OSVersion");
                    _OSVersion = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OSVersion");
                    OnOSVersionChanged();
                }
            }
        }
        private global::System.String _OSVersion;
        partial void OnOSVersionChanging(global::System.String value);
        partial void OnOSVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSType
        {
            get
            {
                return _OSType;
            }
            set
            {
                if (_OSType != value)
                {
                    OnOSTypeChanging(value);
                    ReportPropertyChanging("OSType");
                    _OSType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OSType");
                    OnOSTypeChanged();
                }
            }
        }
        private global::System.String _OSType;
        partial void OnOSTypeChanging(global::System.String value);
        partial void OnOSTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemorySize
        {
            get
            {
                return _MemorySize;
            }
            set
            {
                OnMemorySizeChanging(value);
                ReportPropertyChanging("MemorySize");
                _MemorySize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemorySize");
                OnMemorySizeChanged();
            }
        }
        private global::System.Int32 _MemorySize;
        partial void OnMemorySizeChanging(global::System.Int32 value);
        partial void OnMemorySizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NetConnectionType
        {
            get
            {
                return _NetConnectionType;
            }
            set
            {
                OnNetConnectionTypeChanging(value);
                ReportPropertyChanging("NetConnectionType");
                _NetConnectionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NetConnectionType");
                OnNetConnectionTypeChanged();
            }
        }
        private global::System.String _NetConnectionType;
        partial void OnNetConnectionTypeChanging(global::System.String value);
        partial void OnNetConnectionTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="schema_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class schema_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new schema_info object.
        /// </summary>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="changedBy">Initial value of the ChangedBy property.</param>
        /// <param name="modDate">Initial value of the ModDate property.</param>
        public static schema_info Createschema_info(global::System.String version, global::System.String changedBy, global::System.DateTime modDate)
        {
            schema_info schema_info = new schema_info();
            schema_info.Version = version;
            schema_info.ChangedBy = changedBy;
            schema_info.ModDate = modDate;
            return schema_info;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                if (_Version != value)
                {
                    OnVersionChanging(value);
                    ReportPropertyChanging("Version");
                    _Version = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Version");
                    OnVersionChanged();
                }
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChangedBy
        {
            get
            {
                return _ChangedBy;
            }
            set
            {
                OnChangedByChanging(value);
                ReportPropertyChanging("ChangedBy");
                _ChangedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChangedBy");
                OnChangedByChanged();
            }
        }
        private global::System.String _ChangedBy;
        partial void OnChangedByChanging(global::System.String value);
        partial void OnChangedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModDate
        {
            get
            {
                return _ModDate;
            }
            set
            {
                OnModDateChanging(value);
                ReportPropertyChanging("ModDate");
                _ModDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModDate");
                OnModDateChanged();
            }
        }
        private global::System.DateTime _ModDate;
        partial void OnModDateChanging(global::System.DateTime value);
        partial void OnModDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAT_DTF_ecsModel", Name="testrun")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class testrun : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new testrun object.
        /// </summary>
        /// <param name="fullPath">Initial value of the FullPath property.</param>
        /// <param name="jobID">Initial value of the JobID property.</param>
        /// <param name="runIndex">Initial value of the RunIndex property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="oSImageID">Initial value of the OSImageID property.</param>
        public static testrun Createtestrun(global::System.String fullPath, global::System.String jobID, global::System.Int32 runIndex, global::System.String status, global::System.String oSImageID)
        {
            testrun testrun = new testrun();
            testrun.FullPath = fullPath;
            testrun.JobID = jobID;
            testrun.RunIndex = runIndex;
            testrun.Status = status;
            testrun.OSImageID = oSImageID;
            return testrun;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullPath
        {
            get
            {
                return _FullPath;
            }
            set
            {
                if (_FullPath != value)
                {
                    OnFullPathChanging(value);
                    ReportPropertyChanging("FullPath");
                    _FullPath = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FullPath");
                    OnFullPathChanged();
                }
            }
        }
        private global::System.String _FullPath;
        partial void OnFullPathChanging(global::System.String value);
        partial void OnFullPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                if (_JobID != value)
                {
                    OnJobIDChanging(value);
                    ReportPropertyChanging("JobID");
                    _JobID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("JobID");
                    OnJobIDChanged();
                }
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RunIndex
        {
            get
            {
                return _RunIndex;
            }
            set
            {
                if (_RunIndex != value)
                {
                    OnRunIndexChanging(value);
                    ReportPropertyChanging("RunIndex");
                    _RunIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RunIndex");
                    OnRunIndexChanged();
                }
            }
        }
        private global::System.Int32 _RunIndex;
        partial void OnRunIndexChanging(global::System.Int32 value);
        partial void OnRunIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResultStatus
        {
            get
            {
                return _ResultStatus;
            }
            set
            {
                OnResultStatusChanging(value);
                ReportPropertyChanging("ResultStatus");
                _ResultStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResultStatus");
                OnResultStatusChanged();
            }
        }
        private global::System.String _ResultStatus;
        partial void OnResultStatusChanging(global::System.String value);
        partial void OnResultStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResultSubStatus
        {
            get
            {
                return _ResultSubStatus;
            }
            set
            {
                OnResultSubStatusChanging(value);
                ReportPropertyChanging("ResultSubStatus");
                _ResultSubStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResultSubStatus");
                OnResultSubStatusChanged();
            }
        }
        private global::System.String _ResultSubStatus;
        partial void OnResultSubStatusChanging(global::System.String value);
        partial void OnResultSubStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModTime
        {
            get
            {
                return _ModTime;
            }
            set
            {
                OnModTimeChanging(value);
                ReportPropertyChanging("ModTime");
                _ModTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModTime");
                OnModTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModTime;
        partial void OnModTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OSImageID
        {
            get
            {
                return _OSImageID;
            }
            set
            {
                OnOSImageIDChanging(value);
                ReportPropertyChanging("OSImageID");
                _OSImageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OSImageID");
                OnOSImageIDChanged();
            }
        }
        private global::System.String _OSImageID;
        partial void OnOSImageIDChanging(global::System.String value);
        partial void OnOSImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAT_DTF_ecsModel", "fk_testrun_job1", "job")]
        public job job
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_testrun_job1", "job").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_testrun_job1", "job").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<job> jobReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<job>("AAT_DTF_ecsModel.fk_testrun_job1", "job");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<job>("AAT_DTF_ecsModel.fk_testrun_job1", "job", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
